### ISSUE TITLE
Add possibility to add multiple api_keys and hide application url

### ISSUE THREAD

**Issue by chytreg** [BrandyMint/grape-swagger-rails#32]
In swagger-ui is possible to have multiple api_keys

What do you think about this:
```ruby
GrapeSwaggerRails.options.api_keys = [
  { name: 'X-Organization', type: 'header' },
  { name: 'api_key', type: 'query' },
]

# instead of

GrapeSwaggerRails.options.api_key_name = 'something'
GrapeSwaggerRails.options.api_key_type = 'header'
```

I have implemented this here https://github.com/monterail/grape-swagger-rails/commit/76d092ccb6a8e77de66048dd60f1890fce7ca2c6

Later I can make a pull request

**Comment by unloved** [comment]
As far as I don't work in BrandyMint company any longer and no one from the company is maintaining this project, I forked it to [this repo](https://github.com/TinkerDev/grape-swagger-rails).
Feel free to move your issues and prs there
