### ISSUE TITLE
How to start app using nginx?

### ISSUE THREAD

**Issue by EMRJ** [BrandyMint/grape-swagger-rails#34]
I installed passenger + nginx, swagger UI loads on passenger server standalone i want to integrate with nginx, when i navigate through "http://myswaggerrails.com" it says "Welcome to nginx" but when i navigate to my app like "http://myswaggerrails.com/swagger" it return 404 error for assets below:

"NetworkError: 404 Not Found - http://myswaggerrails.com/assets/grape_swagger_rails/highlight.default.css?body=1"
highlig...?body=1
"NetworkError: 404 Not Found - http://myswaggerrails.com/assets/grape_swagger_rails
etc

In nginx.conf i added root as /home/emrj/projects/grape/public

@unloved Can you help me to start swagger application with nginx

**Comment by unloved** [comment]
As far as I don't work in BrandyMint company any longer and no one from the company is maintaining this project, I forked it to [this repo](https://github.com/TinkerDev/grape-swagger-rails).
Feel free to move your issues and prs there
