### ISSUE TITLE
Hand-pick thirdparty JavaScript

### ISSUE THREAD

**Issue by dblock** [BrandyMint/grape-swagger-rails#36]
If you just use the project out of the box you will end up loading libraries that you may already be loading in your own project, like JQuery.

See https://github.com/wordnik/swagger-ui/issues/551#issuecomment-55672164

**Comment by unloved** [comment]
As far as I don't work in BrandyMint company any longer and no one from the company is maintaining this project, I forked it to [this repo](https://github.com/TinkerDev/grape-swagger-rails).
Feel free to move your issues and prs there
