### ISSUE TITLE
Support for grape-swagger >= 0.8

### ISSUE THREAD

**Issue by fabn** [BrandyMint/grape-swagger-rails#39]
I tried to run this gem against grape-swagger 0.8 but I had some issues, see here https://github.com/fabn/grape-swagger-rails/tree/grape-swagger-0.8 and also https://github.com/tim-vandecasteele/grape-swagger/issues/173

It would be nice to have compatibility for latest dependencies released version.

Thanks.

**Comment by dblock** [comment]
This can be closed, bump @fabn.
