### ISSUE TITLE
Missing template

### ISSUE THREAD

**Issue by theo-bittencourt** [BrandyMint/grape-swagger-rails#42]
Hey you!

I'm receiving a `ActionView::MissingTemplate` when I try to visit the UI docs.  :(

The complete exception is:
```ruby
ActionView::MissingTemplate - Missing template grape_swagger_rails/application/index with {:locale=>[:"pt-BR"], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :arb, :slim]}.
```
I'm on Rails 4.1.
Have someone got the same issue?

Best! Theo

**Comment by jasonzhao3** [comment]
I'm getting the same issue. Anyone could help here?

**Comment by jasonzhao3** [comment]
Hey Theo,

I think I figured out the issue. The mounting is not successful, and your default routes redirects it to index page. Since you didn't specify respond_to json format, you get a missing template error.

**Comment by unloved** [comment]
As far as I don't work in BrandyMint company any longer and no one from the company is maintaining this project, I forked it to [this repo](https://github.com/TinkerDev/grape-swagger-rails).
Feel free to move your issues and prs there
