### ISSUE TITLE
Error when adding multiple custom headers

### ISSUE THREAD

**Issue by theo-bittencourt** [BrandyMint/grape-swagger-rails#43]
Hi!

If I code the code below, only the last one is used on the requests.

```ruby
GrapeSwaggerRails.options.headers['X-Quiz-Api-Id'] = 'xxxxxxx'
GrapeSwaggerRails.options.headers['X-Api-Access-Token'] = 'yyyyyy'
```

Reading your code, I figured out this in [index.html.erb:50](https://github.com/BrandyMint/grape-swagger-rails/blob/master/app/views/grape_swagger_rails/application/index.html.erb#L50).

```ruby
<% GrapeSwaggerRails.options.headers.each_pair do |key, value| %>
  <%=raw "window.authorizations.add('key', new ApiKeyAuthorization('#{CGI.escapeHTML(key)}', '#{CGI.escapeHTML(value)}', 'header'));" %>
<% end %>
```

Seems like you are overwriting the `key` key.

Best! Theo

**Comment by unloved** [comment]
As far as I don't work in BrandyMint company any longer and no one from the company is maintaining this project, I forked it to [this repo](https://github.com/TinkerDev/grape-swagger-rails).
Feel free to move your issues and prs there
