### ISSUE TITLE
Recent change broke things with ruby 1.9.3

### ISSUE THREAD

**Issue by mamccr** [BrandyMint/grape-swagger-rails#44]
Feel free to close this if you don't want to support ruby < 2.0, but I found an issue with a recent change in app/views/grape_swagger_rails/application/index.html.erb:

<%= GrapeSwaggerRails.options.to_h.to_json %>

used to be

<%= GrapeSwaggerRails.options.to_json %>

In ruby < 2.0, to_h isn't a method on OpenStruct, so the whole thing evaluates to 'null', which causes a javascript error to occur when loading the page.  So either a more universal workaround needs to happen to serialize the options, or maybe you could document no support for ruby < 2.0, if that's the intent.

Thanks!

**Comment by swistaczek** [comment]
:+1: 

Temporary monkeypatch: ```ruby
module GrapeSwaggerRails
  class Options
    def to_h
      self.marshal_dump
    end
  end
end
```

**Comment by adamcooper** [comment]
+1 for this issue.  It would be nice to have this (or similar) patch included in gem if it's running in ruby 1.9.

**Comment by mmclead** [comment]
The commit that introduced the is: https://github.com/BrandyMint/grape-swagger-rails/commit/7103e646e60a031607a0b2945305655db299f8a6

**Comment by unloved** [comment]
As far as I don't work in BrandyMint company any longer and no one from the company is maintaining this project, I forked it to [this repo](https://github.com/TinkerDev/grape-swagger-rails).
Feel free to move your issues and prs there
