### ISSUE TITLE
Page not loading the javascript and css files needed for it to work

### ISSUE THREAD

**Issue by gnapse** [BrandyMint/grape-swagger-rails#47]
I have this gem installed in my app, and when I visit the documentation page this is what I get.

![error](https://cloud.githubusercontent.com/assets/15199/5970690/585e0352-a815-11e4-9009-e6e24d54c15d.png)

In the console is evidenced that the web page is not being able to load the css and js needed for it to work. Any ideas on why I'm getting this?

**Comment by unloved** [comment]
As far as I don't work in BrandyMint company any longer and no one from the company is maintaining this project, I forked it to [this repo](https://github.com/TinkerDev/grape-swagger-rails).
Feel free to move your issues and prs there
